language: cpp
sudo: required

install:

 - make -f shCXX

script:
    - if [ "$CXX" = "g++" ]; then g++ --version; fi
    - if [ "$CXX" != "g++" ]; then clang++ --version; fi
    - make clean
    - make
    - ./xlib
compiler:
- clang++
- g++
os:
#- linux
- osx
branches:
 only:
 - master
notifacations:
 email: false
 irc:
 - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
env:
 global:
 - LANG="en_US.UTF-8"
